import './global.css';
import { NavBar } from '../features/navigation/components/nav-bar';

export const metadata = {
  title: 'Welcome to whats-up-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-full flex flex-col bg-violet-50">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
