import './global.css';

export const metadata = {
  title: 'Welcome to whats-up-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="fixed top-0 right-0 bottom-0 left-0">{children}</body>
    </html>
  );
}
